export const questions = [
  "What's her name",
  "How long you've been in a relationship",
  "What are your names?",
  "How long have you been together?",
  "How did you meet?",
  "What is your current relationship status?",
  "Do you live together?",
  "Have you been on any memorable vacations together?",
  "What is your favorite activity to do as a couple?",
  "Have you discussed your long-term goals as a couple?",
  "What is your favorite memory together?",
  "What is something you appreciate about your partner?",
  "Have you met each other's families?",
  "Do you have any pets together?",
  "What is your favorite food to cook together?",
  "Have you ever surprised each other with a romantic gesture?",
  "What is something you have learned about each other that you didn't know before you started dating?",
];
